### ISSUE TITLE
Server should keep track of who created a resource

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid#111]
At the moment, the Solid platform does not have a mechanism to record or discover which user created a resource, even though the server has that information at the time of resource creation (that is, by the time a PUT/POST/PATCH succeeds, the user has been authenticated, and their WebID is known to the server). 
This causes various inconveniences (including not being able to verify the sender of Notifications).
To that end:
- [ ] Implement server-side support for recording the WebID of the user who created a resource (issue [solid-server/#407](https://github.com/solid/node-solid-server/issues/407))
- [ ] Return this information in a header on GET and HEAD requests (issue [solid-server/#408](https://github.com/solid/node-solid-server/issues/408))
- [ ] Add client-side support for parsing this header (issue [solid-client/#113](https://github.com/solid/solid-client/issues/113))

**Comment by dmitrizagidulin** [comment]
Will be handled in https://github.com/solid/specification/issues/63

**Comment by dmitrizagidulin** [comment]
Moved to https://github.com/solid/specification/issues/66, closing.
